- name: Test_Suite1_lama
  model: llama3.2:latest
  grade_model: Gary:latest
  grade_by: 
  - basic_grader.csv
  - echo_grader.csv
  prompts: 
  - fran_base.csv
  - echo.csv
  - fran.csv
  conversations:
  - "simple_conversation.csv"
- name: Test_Suite2_lama
  model: llama3.2:latest
  grade_model: Gary:latest
  grade_by: 
  - basic_grader.csv
  - echo_grader.csv
  prompts: 
  - fran_base.csv
  - echo.csv
  - fran.csv
  conversations:
  - "simple_conversation.csv"
